improved imagemagick downloading and installing

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,7 +5,7 @@ CACHE_DIR=$2
 
 VENDOR_DIR="$BUILD_DIR/vendor"
 INSTALL_DIR="$VENDOR_DIR/imagemagick-webp"
-CACHE_FILE="$CACHE_DIR/imagemagick-webp.tar.gz"
+CACHE_FILE="$CACHE_DIR/imagemagick-webp.tar.xz"
 
 mkdir -p $CACHE_DIR
 mkdir -p $VENDOR_DIR
@@ -66,14 +66,23 @@ if [ ! -f $CACHE_FILE ]; then
   rm -rf $LIBWEBP_DIR
 
   # install imagemagick
-
-  IMAGE_MAGICK_VERSION="6.9.3-10"
+  
+  IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-6.9.3-10}"
   IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.xz"
   IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
+  # SSL cert used on imagemagick not recognized by heroku.
   IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
 
   echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-  curl -L --silent $IMAGE_MAGICK_URL | tar xz
+  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
+  
+  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
+  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+    echo "Error: Unable to download image magick" | indent
+    ls $BUILD_DIR | indent
+    exit 1;
+  fi
+  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
 
   echo "-----> Building ImageMagick"
   cd $IMAGE_MAGICK_DIR
@@ -84,13 +93,14 @@ if [ ! -f $CACHE_FILE ]; then
   cd ..
   rm -rf $IMAGE_MAGICK_DIR
 
+
   # cache for future deploys
 
   echo "-----> Caching ImageMagick and libwebp installation"
   cd $VENDOR_DIR
   REL_INSTALL_DIR="imagemagick-webp"
-  tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
-  mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
+  tar czf $REL_INSTALL_DIR.tar.xz $REL_INSTALL_DIR
+  mv $REL_INSTALL_DIR.tar.xz $CACHE_FILE
 
 else
 
